name: mvvm_getx_weather_app 
description: "A new Flutter project." 
publish_to: 'none' 
version: 1.0.0+1 

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  rename_app: ^1.3.2
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

icons_launcher:
  image_path: "assets/images/clouds.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter:
  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/
